import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { RandomRegionPuzzleGenerator } from '../src/game-core/random-region-generator.ts';

const size = Number(process.argv[2] ?? 6);
const target = Number(process.argv[3] ?? 100);
const outputPath = resolve(process.argv[4] ?? `src/puzzles/random-region-${size}x${size}.generated.ts`);
const firstSeed = Number(process.argv[5] ?? size * 100_000_000);
const maximumSeeds = Number(process.argv[6] ?? target * 10_000);

if (!Number.isInteger(size) || size < 4 || size > 12) throw new Error('Size must be an integer from 4 to 12.');
if (!Number.isInteger(target) || target < 1) throw new Error('Target must be a positive integer.');
if (!Number.isInteger(firstSeed) || firstSeed < 0) throw new Error('First seed must be a non-negative integer.');
if (!Number.isInteger(maximumSeeds) || maximumSeeds < 1) throw new Error('Maximum seeds must be a positive integer.');

const generator = new RandomRegionPuzzleGenerator();
const candidates = [];
const hashes = new Set<string>();
let generatedCandidates = 0;
let failedSeeds = 0;
let duplicateCandidates = 0;

process.stdout.write(
  `Building ${target} unique random-region ${size}x${size} puzzles (max ${maximumSeeds} seeds)...\\n`,
);

for (let offset = 0; hashes.size < target && offset < maximumSeeds; offset += 1) {
  const seed = firstSeed + offset;

  try {
    const generated = generator.generate(size, seed);
    generatedCandidates += 1;

    const hash = generated.regionMap.join(',');
    if (hashes.has(hash)) {
      duplicateCandidates += 1;
      continue;
    }

    hashes.add(hash);
    candidates.push({
      id: `random-${size}x${size}-seed-${seed}`,
      size: generated.size,
      regionMap: generated.regionMap,
      solution: generated.solution,
      solverMetrics: generated.solverMetrics,
    });
  } catch {
    failedSeeds += 1;
  }

  const processed = offset + 1;
  if (processed === 1 || processed % 100 === 0 || hashes.size === target) {
    const successRate = ((generatedCandidates / processed) * 100).toFixed(1);
    process.stdout.write(
      `[${processed}/${maximumSeeds}] unique=${hashes.size}/${target}, solverUnique=${generatedCandidates}, failed=${failedSeeds}, duplicate=${duplicateCandidates}, success=${successRate}%\\n`,
    );
  }
}

if (candidates.length < target) {
  throw new Error(
    `Only generated ${candidates.length}/${target} unique ${size}x${size} puzzles after ${maximumSeeds} seeds.`,
  );
}

const source = `// Generated by scripts/build-random-region-pool.ts. Do not edit by hand.\\nexport const RANDOM_REGION_PUZZLES = ${JSON.stringify(candidates)} as const;\\n`;
await writeFile(outputPath, source, 'utf8');

process.stdout.write(
  `Wrote ${candidates.length} unique random-region ${size}x${size} puzzles to ${outputPath}\\n`,
);
