import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { RegionPuzzleGenerator } from '../src/game-core/generator.ts';
import { rankPuzzlePool, type PuzzlePoolCandidate } from '../src/game-core/levels.ts';
import { campaignBoardSize } from '../src/game-core/progression.ts';
import type { BoardSize, Difficulty } from '../src/game-core/types.ts';

const LAST_BUNDLED_LEVEL = 150;
const outputPath = resolve(process.argv[2] ?? 'src/puzzles/bundled-campaign.generated.ts');
const generator = new RegionPuzzleGenerator();
const candidates: PuzzlePoolCandidate[] = [];
const requiredBySize = new Map<BoardSize, number>();
const levelsBySize = new Map<BoardSize, number[]>();

function demoDifficulty(level: number): Difficulty {
  if (level <= 10) return 'beginner';
  if (level <= 30) return 'intermediate';
  if (level <= 60) return 'advanced';
  if (level <= 100) return 'expert';
  return 'king';
}

for (let level = 1; level <= LAST_BUNDLED_LEVEL; level += 1) {
  const size = campaignBoardSize(level);
  requiredBySize.set(size, (requiredBySize.get(size) ?? 0) + 1);
  const levels = levelsBySize.get(size) ?? [];
  levels.push(level);
  levelsBySize.set(size, levels);
}

// Generate exactly the number of candidates required for each board size.
// The generator already performs the expensive uniqueness check only after a
// complete candidate has been constructed. We deliberately allow many seeds:
// some board sizes have a much lower probability of producing a unique puzzle.
for (const [size, required] of requiredBySize) {
  const hashes = new Set<string>();
  const firstSeed = size * 10_000_000;
  const maximumSeeds = Math.max(required * 500, 10_000);

  for (let offset = 0; hashes.size < required && offset < maximumSeeds; offset += 1) {
    const seed = firstSeed + offset;
    try {
      const generated = generator.generate(size, seed);
      const hash = generated.regionMap.join(',');
      if (hashes.has(hash)) continue;
      hashes.add(hash);
      candidates.push({
        id: `${size}x${size}-seed-${seed}`,
        size,
        regionMap: generated.regionMap,
        solution: generated.solution,
        solverMetrics: generated.solverMetrics,
      });
    } catch {
      // Failed seeds are deterministic and simply skipped.
    }
  }

  if (hashes.size < required) {
    throw new Error(`Only generated ${hashes.size}/${required} unique ${size}x${size} puzzles after ${maximumSeeds} seeds.`);
  }
}

const ranked = rankPuzzlePool(candidates);
const bundled: Array<{
  level: number;
  puzzleId: string;
  size: BoardSize;
  difficulty: Difficulty;
  regionMap: readonly number[];
  givenQueenCellIndexes: number[];
  version: number;
}> = [];

for (const [size, levels] of levelsBySize) {
  const available = ranked
    .filter((candidate) => candidate.size === size)
    .sort((a, b) => a.costScore - b.costScore || a.id.localeCompare(b.id));
  const orderedLevels = [...levels].sort((a, b) => a - b);
  const used = new Set<string>();

  for (let position = 0; position < orderedLevels.length; position += 1) {
    const level = orderedLevels[position]!;
    const difficulty = demoDifficulty(level);
    const remaining = orderedLevels.length - position;
    const unused = available.filter((candidate) => !used.has(candidate.id));
    if (unused.length < remaining) throw new Error(`Insufficient ${size}x${size} candidates for level ${level}.`);

    const spread = Math.max(1, Math.floor(unused.length / remaining));
    const selected = unused[Math.min(position * spread, unused.length - remaining)]!;
    used.add(selected.id);

    const givenSolutionIndexes = difficulty === 'beginner'
      ? [1, size - 2]
      : difficulty === 'intermediate'
        ? [Math.floor(size / 2)]
        : [];
    const givenQueenCellIndexes = givenSolutionIndexes.map((solutionIndex) => {
      const queen = selected.solution[solutionIndex]!;
      return queen.row * size + queen.column;
    });

    bundled.push({
      level,
      puzzleId: `campaign-${level}-${selected.id}`,
      size,
      difficulty,
      regionMap: selected.regionMap,
      givenQueenCellIndexes,
      version: 1,
    });
  }
}

bundled.sort((a, b) => a.level - b.level);
if (bundled.length !== LAST_BUNDLED_LEVEL) throw new Error(`Expected ${LAST_BUNDLED_LEVEL} bundled puzzles, got ${bundled.length}.`);
if (new Set(bundled.map((puzzle) => puzzle.puzzleId)).size !== bundled.length) throw new Error('Bundled puzzle IDs must be unique.');
if (new Set(bundled.map((puzzle) => puzzle.regionMap.join(','))).size !== bundled.length) throw new Error('Every bundled puzzle must have a unique region topology.');

const source = `// Generated by scripts/build-bundled-campaign.ts. Do not edit by hand.\nexport const BUNDLED_CAMPAIGN_PUZZLES = ${JSON.stringify(bundled)} as const;\n`;
await writeFile(outputPath, source, 'utf8');
process.stdout.write(`Wrote ${bundled.length} unique bundled campaign puzzles to ${outputPath}\n`);
