import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { RegionPuzzleGenerator } from '../src/game-core/generator.ts';
import { rankPuzzlePool, type RankedPuzzleCandidate } from '../src/game-core/levels.ts';
import { campaignBoardSize } from '../src/game-core/progression.ts';
import type { BoardSize, Difficulty } from '../src/game-core/types.ts';

const LAST_BUNDLED_LEVEL = 150;
const TARGET_PER_SIZE = 160;
const outputPath = resolve(process.argv[2] ?? 'src/puzzles/bundled-campaign.generated.ts');
const generator = new RegionPuzzleGenerator();
const sizes = [...new Set(Array.from({ length: LAST_BUNDLED_LEVEL }, (_, index) => campaignBoardSize(index + 1)))] as BoardSize[];
const candidates: RankedPuzzleCandidate[] = [];

for (const size of sizes) {
  const hashes = new Set<string>();
  const firstSeed = size * 10_000_000;
  const maximumSeeds = TARGET_PER_SIZE * 1_000;
  for (let seed = firstSeed; hashes.size < TARGET_PER_SIZE && seed < firstSeed + maximumSeeds; seed += 1) {
    try {
      const generated = generator.generate(size, seed);
      const hash = generated.regionMap.join(',');
      if (hashes.has(hash)) continue;
      hashes.add(hash);
      candidates.push({ id: `${size}x${size}-seed-${seed}`, size, regionMap: generated.regionMap, solution: generated.solution, solverMetrics: generated.solverMetrics });
    } catch { /* Deterministic failed seeds are skipped. */ }
  }
  if (hashes.size < TARGET_PER_SIZE) throw new Error(`Only generated ${hashes.size}/${TARGET_PER_SIZE} unique ${size}x${size} puzzles.`);
}

const ranked = rankPuzzlePool(candidates);
const used = new Set<string>();
const bundled = [];

function demoDifficulty(level: number): Difficulty {
  if (level <= 10) return 'beginner';
  if (level <= 30) return 'intermediate';
  if (level <= 60) return 'advanced';
  if (level <= 100) return 'expert';
  return 'king';
}

for (let level = 1; level <= LAST_BUNDLED_LEVEL; level += 1) {
  const size = campaignBoardSize(level);
  const difficulty = demoDifficulty(level);
  const eligible = ranked
    .filter((candidate) => candidate.size === size && candidate.costTier === difficulty && !used.has(candidate.id))
    .sort((a, b) => a.costScore - b.costScore || a.id.localeCompare(b.id));
  if (!eligible.length) throw new Error(`No unused ${size}x${size} ${difficulty} candidate remains for level ${level}.`);
  const mixed = Math.imul(level ^ 0x7f4a7c15, 0x9e3779b1) >>> 0;
  const selected: RankedPuzzleCandidate = eligible[mixed % eligible.length]!;
  used.add(selected.id);
  const givenSolutionIndexes = difficulty === 'beginner'
    ? [1, size - 2]
    : difficulty === 'intermediate'
      ? [Math.floor(size / 2)]
      : [];
  const givenQueenCellIndexes = givenSolutionIndexes.map((solutionIndex) => {
    const position = selected.solution[solutionIndex]!;
    return position.row * size + position.column;
  });
  bundled.push({ level, puzzleId: `campaign-${level}-${selected.id}`, size, difficulty, regionMap: selected.regionMap, givenQueenCellIndexes, version: 1 });
}

if (bundled.length !== LAST_BUNDLED_LEVEL) throw new Error(`Expected ${LAST_BUNDLED_LEVEL} bundled puzzles, got ${bundled.length}.`);
if (new Set(bundled.map((puzzle) => puzzle.puzzleId)).size !== bundled.length) throw new Error('Bundled puzzle IDs must be unique.');

const source = `// Generated by scripts/build-bundled-campaign.ts. Do not edit by hand.\nexport const BUNDLED_CAMPAIGN_PUZZLES = ${JSON.stringify(bundled)} as const;\n`;
await writeFile(outputPath, source, 'utf8');
process.stdout.write(`Wrote ${bundled.length} unique bundled campaign puzzles to ${outputPath}\n`);
