import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { RandomRegionPuzzleGenerator } from '../src/game-core/random-region-generator.ts';

const size = Number(process.argv[2] ?? 6);
const target = Number(process.argv[3] ?? 100);
const outputPath = resolve(process.argv[4] ?? `src/puzzles/random-region-${size}x${size}.generated.ts`);

if (!Number.isInteger(size) || size < 4 || size > 12) throw new Error('Size must be an integer from 4 to 12.');
if (!Number.isInteger(target) || target < 1) throw new Error('Target must be a positive integer.');

const generator = new RandomRegionPuzzleGenerator();
const candidates = [];
const hashes = new Set<string>();
const firstSeed = size * 100_000_000;
const maximumSeeds = target * 10_000;

for (let seed = firstSeed; hashes.size < target && seed < firstSeed + maximumSeeds; seed += 1) {
  try {
    const generated = generator.generate(size, seed);
    const hash = generated.regionMap.join(',');
    if (hashes.has(hash)) continue;
    hashes.add(hash);
    candidates.push({
      id: `random-${size}x${size}-seed-${seed}`,
      size: generated.size,
      regionMap: generated.regionMap,
      solution: generated.solution,
      solverMetrics: generated.solverMetrics,
    });
  } catch {
    // Random seeds that fail the uniqueness filter are skipped.
  }
}

if (candidates.length < target) {
  throw new Error(`Only generated ${candidates.length}/${target} unique ${size}x${size} puzzles.`);
}

const source = `// Generated by scripts/build-random-region-pool.ts. Do not edit by hand.\\nexport const RANDOM_REGION_PUZZLES = ${JSON.stringify(candidates)} as const;\\n`;
await writeFile(outputPath, source, 'utf8');
process.stdout.write(`Wrote ${candidates.length} unique random-region ${size}x${size} puzzles to ${outputPath}\\n`);
